# Generated by Django 3.1.5 on 2021-01-30 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Список видов товаров',
                'db_table': 'goods_type',
            },
        ),
        migrations.CreateModel(
            name='GoodsShopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=150)),
                ('weight', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, default='', upload_to='range/img', verbose_name='Фото')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='range.typegoods')),
            ],
            options={
                'verbose_name': 'Список товаров',
                'db_table': 'goods_shop',
            },
        ),
    ]
